//
// AQCurrent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AQCurrent: Codable {
    /// Cloud cover as a percentage (%)
    public var aqi: Int?
    /// Concentration of SO2 (Âµg/mÂ³)
    public var so2: Double?
    /// Concentration of NO2 (Âµg/mÂ³)
    public var no2: Double?
    /// Concentration of O3 (Âµg/mÂ³)
    public var o3: Double?
    /// Concentration of PM 2.5 (Âµg/mÂ³)
    public var pm25: Double?
    /// Concentration of PM 10 (Âµg/mÂ³)
    public var pm10: Double?

    public init(aqi: Int? = nil, so2: Double? = nil, no2: Double? = nil, o3: Double? = nil, pm25: Double? = nil, pm10: Double? = nil) {
        self.aqi = aqi
        self.so2 = so2
        self.no2 = no2
        self.o3 = o3
        self.pm25 = pm25
        self.pm10 = pm10
    }
}
