//
// CurrentObsGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CurrentObsGroup: Codable {
    /// Count of found observations
    public var count: Int?
    public var data: [CurrentObs]?

    public init(count: Int? = nil, data: [CurrentObs]? = nil) {
        self.count = count
        self.data = data
    }
}
