//
// Forecast.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Forecast: Codable {
    /// Unix Timestamp
    public var ts: Double?
    /// Timestamp in local time
    public var timestampLocal: String?
    /// Timestamp UTC
    public var timestampUtc: String?
    /// Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)
    public var datetime: String?
    /// Accumulated snowfall since last forecast point - default (mm)
    public var snow: Double?
    /// Snow Depth - default (mm)
    public var snowDepth: Double?
    /// Accumulated precipitation since last forecast point - default (mm)
    public var precip: Double?
    /// Temperature (Average) - default (C)
    public var temp: Double?
    /// Dewpoint (Average) - default (C)
    public var dewpt: Double?
    /// Maximum daily Temperature - default (C)
    public var maxTemp: Double?
    /// Minimum daily Temperature - default (C)
    public var minTemp: Double?
    /// Apparent Maximum daily Temperature - default (C)
    public var appMaxTemp: Double?
    /// Apparent Minimum daily Temperature - default (C)
    public var appMinTemp: Double?
    /// Relative Humidity as a percentage (%)
    public var rh: Int?
    /// Cloud cover as a percentage (%)
    public var clouds: Int?
    public var weather: ForecastWeather?
    /// Mean Sea level pressure (mb)
    public var slp: Double?
    /// Pressure (mb)
    public var pres: Double?
    /// UV Index
    public var uv: Double?
    /// [Deprecated] Max direct component of solar insolation (W/m^2)
    public var maxDhi: Double?
    /// Average Visibility default (KM)
    public var vis: Double?
    /// Chance of Precipitation as a percentage (%)
    public var pop: Double?
    /// Moon phase
    public var moonPhase: Double?
    /// Sunrise unix timestamp
    public var sunriseTs: Int?
    /// Sunset unix timestamp
    public var sunsetTs: Int?
    /// Moonrise unix timestamp
    public var moonriseTs: Int?
    /// Moonset unix timestamp
    public var moonsetTs: Int?
    /// Part of the day (d = day, n = night)
    public var pod: String?
    /// Wind Speed (default m/s)
    public var windSpd: Double?
    /// Wind direction
    public var windDir: Int?
    /// Cardinal wind direction
    public var windCdir: String?
    /// Cardinal wind direction (text)
    public var windCdirFull: String?

    public init(ts: Double? = nil, timestampLocal: String? = nil, timestampUtc: String? = nil, datetime: String? = nil, snow: Double? = nil, snowDepth: Double? = nil, precip: Double? = nil, temp: Double? = nil, dewpt: Double? = nil, maxTemp: Double? = nil, minTemp: Double? = nil, appMaxTemp: Double? = nil, appMinTemp: Double? = nil, rh: Int? = nil, clouds: Int? = nil, weather: ForecastWeather? = nil, slp: Double? = nil, pres: Double? = nil, uv: Double? = nil, maxDhi: Double? = nil, vis: Double? = nil, pop: Double? = nil, moonPhase: Double? = nil, sunriseTs: Int? = nil, sunsetTs: Int? = nil, moonriseTs: Int? = nil, moonsetTs: Int? = nil, pod: String? = nil, windSpd: Double? = nil, windDir: Int? = nil, windCdir: String? = nil, windCdirFull: String? = nil) {
        self.ts = ts
        self.timestampLocal = timestampLocal
        self.timestampUtc = timestampUtc
        self.datetime = datetime
        self.snow = snow
        self.snowDepth = snowDepth
        self.precip = precip
        self.temp = temp
        self.dewpt = dewpt
        self.maxTemp = maxTemp
        self.minTemp = minTemp
        self.appMaxTemp = appMaxTemp
        self.appMinTemp = appMinTemp
        self.rh = rh
        self.clouds = clouds
        self.weather = weather
        self.slp = slp
        self.pres = pres
        self.uv = uv
        self.maxDhi = maxDhi
        self.vis = vis
        self.pop = pop
        self.moonPhase = moonPhase
        self.sunriseTs = sunriseTs
        self.sunsetTs = sunsetTs
        self.moonriseTs = moonriseTs
        self.moonsetTs = moonsetTs
        self.pod = pod
        self.windSpd = windSpd
        self.windDir = windDir
        self.windCdir = windCdir
        self.windCdirFull = windCdirFull
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ts
        case timestampLocal = "timestamp_local"
        case timestampUtc = "timestamp_utc"
        case datetime
        case snow
        case snowDepth = "snow_depth"
        case precip
        case temp
        case dewpt
        case maxTemp = "max_temp"
        case minTemp = "min_temp"
        case appMaxTemp = "app_max_temp"
        case appMinTemp = "app_min_temp"
        case rh
        case clouds
        case weather
        case slp
        case pres
        case uv
        case maxDhi = "max_dhi"
        case vis
        case pop
        case moonPhase = "moon_phase"
        case sunriseTs = "sunrise_ts"
        case sunsetTs = "sunset_ts"
        case moonriseTs = "moonrise_ts"
        case moonsetTs = "moonset_ts"
        case pod
        case windSpd = "wind_spd"
        case windDir = "wind_dir"
        case windCdir = "wind_cdir"
        case windCdirFull = "wind_cdir_full"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        ts = try container.decodeIfPresent(Double.self, forKey: .ts)
        timestampLocal = try container.decodeIfPresent(String.self, forKey: .timestampLocal)
        timestampUtc = try container.decodeIfPresent(String.self, forKey: .timestampUtc)
        datetime = try container.decodeIfPresent(String.self, forKey: .datetime)
        snow = try container.decodeIfPresent(Double.self, forKey: .snow)
        snowDepth = try container.decodeIfPresent(Double.self, forKey: .snowDepth)
        precip = try container.decodeIfPresent(Double.self, forKey: .precip)
        temp = try container.decodeIfPresent(Double.self, forKey: .temp)
        dewpt = try container.decodeIfPresent(Double.self, forKey: .dewpt)
        maxTemp = try container.decodeIfPresent(Double.self, forKey: .maxTemp)
        minTemp = try container.decodeIfPresent(Double.self, forKey: .minTemp)
        appMaxTemp = try container.decodeIfPresent(Double.self, forKey: .appMaxTemp)
        appMinTemp = try container.decodeIfPresent(Double.self, forKey: .appMinTemp)
        rh = try container.decodeIfPresent(Int.self, forKey: .rh)
        clouds = try container.decodeIfPresent(Int.self, forKey: .clouds)
        weather = try container.decodeIfPresent(ForecastWeather.self, forKey: .weather)
        slp = try container.decodeIfPresent(Double.self, forKey: .slp)
        pres = try container.decodeIfPresent(Double.self, forKey: .pres)
        uv = try container.decodeIfPresent(Double.self, forKey: .uv)
        maxDhi = try container.decodeIfPresent(Double.self, forKey: .maxDhi)
        vis = try container.decodeIfPresent(Double.self, forKey: .vis)
        pop = try container.decodeIfPresent(Double.self, forKey: .pop)
        moonPhase = try container.decodeIfPresent(Double.self, forKey: .moonPhase)
        sunriseTs = try container.decodeIfPresent(Int.self, forKey: .sunriseTs)
        sunsetTs = try container.decodeIfPresent(Int.self, forKey: .sunsetTs)
        moonriseTs = try container.decodeIfPresent(Int.self, forKey: .moonriseTs)
        moonsetTs = try container.decodeIfPresent(Int.self, forKey: .moonsetTs)
        pod = try container.decodeIfPresent(String.self, forKey: .pod)
        windSpd = try container.decodeIfPresent(Double.self, forKey: .windSpd)
        windDir = try container.decodeIfPresent(Int.self, forKey: .windDir)
        windCdir = try container.decodeIfPresent(String.self, forKey: .windCdir)
        windCdirFull = try container.decodeIfPresent(String.self, forKey: .windCdirFull)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ts, forKey: .ts)
        try container.encodeIfPresent(timestampLocal, forKey: .timestampLocal)
        try container.encodeIfPresent(timestampUtc, forKey: .timestampUtc)
        try container.encodeIfPresent(datetime, forKey: .datetime)
        try container.encodeIfPresent(snow, forKey: .snow)
        try container.encodeIfPresent(snowDepth, forKey: .snowDepth)
        try container.encodeIfPresent(precip, forKey: .precip)
        try container.encodeIfPresent(temp, forKey: .temp)
        try container.encodeIfPresent(dewpt, forKey: .dewpt)
        try container.encodeIfPresent(maxTemp, forKey: .maxTemp)
        try container.encodeIfPresent(minTemp, forKey: .minTemp)
        try container.encodeIfPresent(appMaxTemp, forKey: .appMaxTemp)
        try container.encodeIfPresent(appMinTemp, forKey: .appMinTemp)
        try container.encodeIfPresent(rh, forKey: .rh)
        try container.encodeIfPresent(clouds, forKey: .clouds)
        try container.encodeIfPresent(weather, forKey: .weather)
        try container.encodeIfPresent(slp, forKey: .slp)
        try container.encodeIfPresent(pres, forKey: .pres)
        try container.encodeIfPresent(uv, forKey: .uv)
        try container.encodeIfPresent(maxDhi, forKey: .maxDhi)
        try container.encodeIfPresent(vis, forKey: .vis)
        try container.encodeIfPresent(pop, forKey: .pop)
        try container.encodeIfPresent(moonPhase, forKey: .moonPhase)
        try container.encodeIfPresent(sunriseTs, forKey: .sunriseTs)
        try container.encodeIfPresent(sunsetTs, forKey: .sunsetTs)
        try container.encodeIfPresent(moonriseTs, forKey: .moonriseTs)
        try container.encodeIfPresent(moonsetTs, forKey: .moonsetTs)
        try container.encodeIfPresent(pod, forKey: .pod)
        try container.encodeIfPresent(windSpd, forKey: .windSpd)
        try container.encodeIfPresent(windDir, forKey: .windDir)
        try container.encodeIfPresent(windCdir, forKey: .windCdir)
        try container.encodeIfPresent(windCdirFull, forKey: .windCdirFull)
    }
}
