//
// HistoryObjWeather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HistoryObjWeather: Codable {
    /// Icon code for forecast image display
    public var icon: String?
    /// Weather Condition code
    public var code: String?
    /// Weather Condition description
    public var description: String?

    public init(icon: String? = nil, code: String? = nil, description: String? = nil) {
        self.icon = icon
        self.code = code
        self.description = description
    }
}
