//
// WeatherAlert.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WeatherAlert: Codable {
    /// Latitude
    public var lat: Double?
    /// Longitude
    public var lon: Double?
    public var alerts: [WeatherAlertGroup]?

    public init(lat: Double? = nil, lon: Double? = nil, alerts: [WeatherAlertGroup]? = nil) {
        self.lat = lat
        self.lon = lon
        self.alerts = alerts
    }
}
