//
// ContextPhotos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContextPhotos: Codable {
    public var photos: [ContextPhoto]?

    public init(photos: [ContextPhoto]? = nil) {
        self.photos = photos
    }
}
