//
// Cover.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Cover: Codable {
    public var id: String?
    public var owner: String?
    public var secret: String?
    public var server: String?
    public var farm: String?
    public var title: String?
    public var ispublic: Bool?
    public var isfriend: Bool?
    public var isfamily: Bool?
    public var y: String?

    public init(id: String? = nil, owner: String? = nil, secret: String? = nil, server: String? = nil, farm: String? = nil, title: String? = nil, ispublic: Bool? = nil, isfriend: Bool? = nil, isfamily: Bool? = nil, y: String? = nil) {
        self.id = id
        self.owner = owner
        self.secret = secret
        self.server = server
        self.farm = farm
        self.title = title
        self.ispublic = ispublic
        self.isfriend = isfriend
        self.isfamily = isfamily
        self.y = y
    }
}
