//
// Echo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Echo200Response: Codable {
    public var echo: GetFavoritesContextByID200ResponseCount?

    public init(echo: GetFavoritesContextByID200ResponseCount? = nil) {
        self.echo = echo
    }
}
