//
// GetAlbumByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAlbumByID200Response: Codable {
    public var photoset: [Photo]?

    public init(photoset: [Photo]? = nil) {
        self.photoset = photoset
    }
}
