//
// GetAlbumsByPersonID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAlbumsByPersonID200Response: Codable {
    public var page: Double?
    public var pages: Double?
    public var perpage: Double?
    public var total: Double?
    public var photosets: [Album]?

    public init(page: Double? = nil, pages: Double? = nil, perpage: Double? = nil, total: Double? = nil, photosets: [Album]? = nil) {
        self.page = page
        self.pages = pages
        self.perpage = perpage
        self.total = total
        self.photosets = photosets
    }
}
