//
// GetFavoritesContextByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetFavoritesContextByID200Response: Codable {
    public var count: GetFavoritesContextByID200ResponseCount?
    public var prevphoto: ContextPhoto?
    public var nextphoto: ContextPhoto?
    public var stat: String?

    public init(count: GetFavoritesContextByID200ResponseCount? = nil, prevphoto: ContextPhoto? = nil, nextphoto: ContextPhoto? = nil, stat: String? = nil) {
        self.count = count
        self.prevphoto = prevphoto
        self.nextphoto = nextphoto
        self.stat = stat
    }
}
