//
// GetFavoritesContextByID200ResponseCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetFavoritesContextByID200ResponseCount: Codable {
    public var content: String?

    public init(content: String? = nil) {
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content = "_content"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        content = try container.decodeIfPresent(String.self, forKey: .content)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(content, forKey: .content)
    }
}
