//
// GetGroupPhotosByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetGroupPhotosByID200Response: Codable {
    public var photos: [Photo]?

    public init(photos: [Photo]? = nil) {
        self.photos = photos
    }
}
