//
// GetGroupTopicRepliesByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetGroupTopicRepliesByID200Response: Codable {
    public var reply: TopicReply?
    public var stat: String?

    public init(reply: TopicReply? = nil, stat: String? = nil) {
        self.reply = reply
        self.stat = stat
    }
}
