//
// GetLicenseByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetLicenseByID200Response: Codable {
    public var licenses: GetLicenseByID200ResponseLicenses?
    public var stat: String?

    public init(licenses: GetLicenseByID200ResponseLicenses? = nil, stat: String? = nil) {
        self.licenses = licenses
        self.stat = stat
    }
}
