//
// GetPhotoSizesByID200ResponseSizes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPhotoSizesByID200ResponseSizes: Codable {
    public var canblog: Double?
    public var canprint: Double?
    public var candownload: Double?
    public var sizes: [Size]?

    public init(canblog: Double? = nil, canprint: Double? = nil, candownload: Double? = nil, sizes: [Size]? = nil) {
        self.canblog = canblog
        self.canprint = canprint
        self.candownload = candownload
        self.sizes = sizes
    }
}
