//
// GetPhotoSizesByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPhotoSizesByID200Response: Codable {
    public var sizes: GetPhotoSizesByID200ResponseSizes?
    public var stat: String?

    public init(sizes: GetPhotoSizesByID200ResponseSizes? = nil, stat: String? = nil) {
        self.sizes = sizes
        self.stat = stat
    }
}
