//
// GetPersonByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPersonByID200Response: Codable {
    public var person: Person?
    public var stat: String?

    public init(person: Person? = nil, stat: String? = nil) {
        self.person = person
        self.stat = stat
    }
}
