//
// GetPhotoExifByID200ResponsePhoto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPhotoExifByID200ResponsePhoto: Codable {
    public var id: String?
    public var secret: String?
    public var server: String?
    public var farm: String?
    public var camera: String?
    public var exif: [GetPhotoExifByID200ResponsePhotoExifInner]?

    public init(id: String? = nil, secret: String? = nil, server: String? = nil, farm: String? = nil, camera: String? = nil, exif: [GetPhotoExifByID200ResponsePhotoExifInner]? = nil) {
        self.id = id
        self.secret = secret
        self.server = server
        self.farm = farm
        self.camera = camera
        self.exif = exif
    }
}
