//
// GetPhotoByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPhotoByID200Response: Codable {
    public var photo: Photo?
    public var stat: String?

    public init(photo: Photo? = nil, stat: String? = nil) {
        self.photo = photo
        self.stat = stat
    }
}
