//
// ModelURL.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelURL: Codable {
    public var type: String?
    public var content: String?

    public init(type: String? = nil, content: String? = nil) {
        self.type = type
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case content = "_content"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        type = try container.decodeIfPresent(String.self, forKey: .type)
        content = try container.decodeIfPresent(String.self, forKey: .content)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(content, forKey: .content)
    }
}
