//
// Note.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Note: Codable {
    public var description: String?

    public init(description: String? = nil) {
        self.description = description
    }
}
