//
// PersonPhotos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PersonPhotos: Codable {
    public var firstdatetaken: GetFavoritesContextByID200ResponseCount?
    public var firstdate: GetFavoritesContextByID200ResponseCount?
    public var count: GetFavoritesContextByID200ResponseCount?
    public var views: GetFavoritesContextByID200ResponseCount?

    public init(firstdatetaken: GetFavoritesContextByID200ResponseCount? = nil, firstdate: GetFavoritesContextByID200ResponseCount? = nil, count: GetFavoritesContextByID200ResponseCount? = nil, views: GetFavoritesContextByID200ResponseCount? = nil) {
        self.firstdatetaken = firstdatetaken
        self.firstdate = firstdate
        self.count = count
        self.views = views
    }
}
