//
// PhotoPeople.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoPeople: Codable {
    public var haspeople: Bool?

    public init(haspeople: Bool? = nil) {
        self.haspeople = haspeople
    }
}
