//
// PhotoNotes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoNotes: Codable {
    public var note: [Note]?

    public init(note: [Note]? = nil) {
        self.note = note
    }
}
