//
// PhotoTags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoTags: Codable {
    public var tag: [Tag]?

    public init(tag: [Tag]? = nil) {
        self.tag = tag
    }
}
