//
// PhotoUrls.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoUrls: Codable {
    public var url: [ModelURL]?

    public init(url: [ModelURL]? = nil) {
        self.url = url
    }
}
