//
// PhotoPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoPermissions: Codable {
    public var permcomment: String?
    public var permaddmeta: String?

    public init(permcomment: String? = nil, permaddmeta: String? = nil) {
        self.permcomment = permcomment
        self.permaddmeta = permaddmeta
    }
}
