//
// PhotoVisibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoVisibility: Codable {
    public var ispublic: Bool?
    public var isfriend: Bool?
    public var isfamily: Bool?

    public init(ispublic: Bool? = nil, isfriend: Bool? = nil, isfamily: Bool? = nil) {
        self.ispublic = ispublic
        self.isfriend = isfriend
        self.isfamily = isfamily
    }
}
