//
// PhotoUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PhotoUsage: Codable {
    public var candownload: Bool?
    public var canblog: Bool?
    public var canprint: Bool?
    public var canshare: Bool?

    public init(candownload: Bool? = nil, canblog: Bool? = nil, canprint: Bool? = nil, canshare: Bool? = nil) {
        self.candownload = candownload
        self.canblog = canblog
        self.canprint = canprint
        self.canshare = canshare
    }
}
