//
// Size.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Size: Codable {
    public var label: String?
    public var width: Double?
    public var height: Double?
    public var source: String?
    public var url: String?
    public var media: String?

    public init(label: String? = nil, width: Double? = nil, height: Double? = nil, source: String? = nil, url: String? = nil, media: String? = nil) {
        self.label = label
        self.width = width
        self.height = height
        self.source = source
        self.url = url
        self.media = media
    }
}
