//
// TopicReply.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TopicReply: Codable {
    public var id: String?
    public var message: GetFavoritesContextByID200ResponseCount?
    public var author: String?
    public var authorname: String?
    public var authorPathAlias: String?
    public var authorIsDeleted: Bool?
    public var isPro: Bool?
    public var iconserver: String?
    public var iconfarm: String?
    public var canEdit: Bool?
    public var canDelete: Bool?
    public var datecreate: String?
    public var lastedit: String?

    public init(id: String? = nil, message: GetFavoritesContextByID200ResponseCount? = nil, author: String? = nil, authorname: String? = nil, authorPathAlias: String? = nil, authorIsDeleted: Bool? = nil, isPro: Bool? = nil, iconserver: String? = nil, iconfarm: String? = nil, canEdit: Bool? = nil, canDelete: Bool? = nil, datecreate: String? = nil, lastedit: String? = nil) {
        self.id = id
        self.message = message
        self.author = author
        self.authorname = authorname
        self.authorPathAlias = authorPathAlias
        self.authorIsDeleted = authorIsDeleted
        self.isPro = isPro
        self.iconserver = iconserver
        self.iconfarm = iconfarm
        self.canEdit = canEdit
        self.canDelete = canDelete
        self.datecreate = datecreate
        self.lastedit = lastedit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case message
        case author
        case authorname
        case authorPathAlias = "author_path_alias"
        case authorIsDeleted = "author_is_deleted"
        case isPro = "is_pro"
        case iconserver
        case iconfarm
        case canEdit = "can_edit"
        case canDelete = "can_delete"
        case datecreate
        case lastedit
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(String.self, forKey: .id)
        message = try container.decodeIfPresent(GetFavoritesContextByID200ResponseCount.self, forKey: .message)
        author = try container.decodeIfPresent(String.self, forKey: .author)
        authorname = try container.decodeIfPresent(String.self, forKey: .authorname)
        authorPathAlias = try container.decodeIfPresent(String.self, forKey: .authorPathAlias)
        authorIsDeleted = try container.decodeIfPresent(Bool.self, forKey: .authorIsDeleted)
        isPro = try container.decodeIfPresent(Bool.self, forKey: .isPro)
        iconserver = try container.decodeIfPresent(String.self, forKey: .iconserver)
        iconfarm = try container.decodeIfPresent(String.self, forKey: .iconfarm)
        canEdit = try container.decodeIfPresent(Bool.self, forKey: .canEdit)
        canDelete = try container.decodeIfPresent(Bool.self, forKey: .canDelete)
        datecreate = try container.decodeIfPresent(String.self, forKey: .datecreate)
        lastedit = try container.decodeIfPresent(String.self, forKey: .lastedit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(authorname, forKey: .authorname)
        try container.encodeIfPresent(authorPathAlias, forKey: .authorPathAlias)
        try container.encodeIfPresent(authorIsDeleted, forKey: .authorIsDeleted)
        try container.encodeIfPresent(isPro, forKey: .isPro)
        try container.encodeIfPresent(iconserver, forKey: .iconserver)
        try container.encodeIfPresent(iconfarm, forKey: .iconfarm)
        try container.encodeIfPresent(canEdit, forKey: .canEdit)
        try container.encodeIfPresent(canDelete, forKey: .canDelete)
        try container.encodeIfPresent(datecreate, forKey: .datecreate)
        try container.encodeIfPresent(lastedit, forKey: .lastedit)
    }
}
